### ISSUE TITLE
Memory ponyfill not working

### ISSUE THREAD

**Issue by sgwilym** [aaronhuggins/indexeddb#1]
I'd love to use this for testing some IndexedDB things in Deno! However, when I try to use the in-memory version of your polyfill, I get a `DOMException` error with `no such table: dbVersions`.

**Comment by aaronhuggins** [comment]
Hi Sam,
  

  
Would you mind providing Deno version, OS version, and some sample code for reproduction purposes?
  

  

  

  
  
  
  
  
>

**Comment by sgwilym** [comment]
Deno version: 1.19.0
OS: macOS 12.1
Sample code: I have only tried to drop your shim into a pretty big codebase, I’ll see if I can put together a smaller example that can reproduce the issue.

**Comment by aaronhuggins** [comment]
@sgwilym If I can get a sample that reproduces your issue, I'll happily add some tests and try to trace if it is a problem with my shim code, my WebSQL imlementation, or the IndexedDBShim codebase.

**Comment by aaronhuggins** [comment]
@sgwilym I was able to reproduce the issue in my own private project. I added tests which should catch a regression in the future.

This defect is fixed in v1.0.1 and the new version has been released.

**Comment by sgwilym** [comment]
Thanks so much for looking into this! Looking forward to trying it out. :)
