### ISSUE TITLE
Re-export internals types and implementations.

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [aaronhuggins/indexeddb#2]
It's useful to have access to types and implementations of internals such as `IDBKeyRange`. Since types are meant to be generic, maybe it would make sense to have a separate package that mirrors the `TypeScript` `lib.dom.ts` definitions. For implementations, I think it makes sense to reexport whatever `indexeddbshim` so that users of this library do not have to know where the implementations come from.

**Comment by aaronhuggins** [comment]
This is a good idea. I actually copy the IndexedDB types from `lib.dom.ts` and include them. However, I'm not currently re-exporting the types in pony/polyfills, except minimally.

I'll give some thought to the best way to go about the export.

**Comment by aaronhuggins** [comment]
The copy of `lib.dom.ts` is because `indexeddbshim` does not export it's own types, but instead depends on TypeScript DOM built-ins.

Since DOM types aren't shipped by default by Deno, I cherry-pick the IndexedDB and related types, and I ship them here.

**Comment by aaronhuggins** [comment]
@make-github-pseudonymous-again Please take a look at branch https://github.com/aaronhuggins/indexeddb/tree/increase-api-surface

I think it does what you are asking for.

**Comment by make-github-pseudonymous-again** [comment]
Yep!

**Comment by aaronhuggins** [comment]
Okay, I actually messed around quite a bit so that exports, IDE type hinting, and docs are all aligned.

Here's a link to Deno doc in the current repo: https://doc.deno.land/https://raw.githubusercontent.com/aaronhuggins/indexeddb/main/ponyfill.ts

Let me know what you think. I'll probably cut a release tomorrow.

**Comment by make-github-pseudonymous-again** [comment]
That look perfect!

**Comment by aaronhuggins** [comment]
Released version 1.1.0:

https://deno.land/x/indexeddb@v1.1.0

https://doc.deno.land/https://deno.land/x/indexeddb@v1.1.0/ponyfill.ts
