### ISSUE TITLE
Polyfill typings: IDBKeyRange only refers to a type

### ISSUE THREAD

**Issue by sgwilym** [aaronhuggins/indexeddb#3]
Hey there! I'm using this module in a bit of a strange way, and am having some trouble with typings.

I'm importing the polyfill in test files. The reason for this is that I am re-exporting this package to a NPM distribution using `dnt`, in a context where IndexedDB will already be provided for.

Once I've imported the polyfill, typings for IndexedDB more or less work in other files, even without importing anything. Except for one thing:

```
TS2693 [ERROR]: 'IDBKeyRange' only refers to a type, but is being used as a value here.
      const range = IDBKeyRange.bound(
                    ~~~~~~~~~~~
```

I can fix this by importing the ponyfill, but then the types clash with the built-in ones from TS when I port this through `dnt`. Is there something I'm missing?

**Comment by aaronhuggins** [comment]
Sam, which version are you using? Please make sure it's the latest at https://deno.land/x/indexeddb

**Comment by sgwilym** [comment]
This is when I’m using v1.3.4.

**Comment by aaronhuggins** [comment]
Sam, please try 1.3.5 when you have a chance. Should show up in a few minutes.

**Comment by sgwilym** [comment]
Thank you, 1.3.5 fixed it!
